### ISSUE TITLE
Shared lock on local read

### ISSUE THREAD

**Issue by GDmac** [thephpleague/flysystem#1025]
### Question
The Adapter for local filesystem uses LOCK_EX for writes,

https://github.com/thephpleague/flysystem/blob/master/src/Adapter/Local.php#L220-L230
Would it be advisable to also use a lock LOCK_SH for reads? e.g.
```php
$tmp = fopen($path, 'rb');
@flock($tmp, LOCK_SH); // note: blocking
$contents = file_get_contents($path);
@flock($tmp, LOCK_UN);
fclose($tmp);
```
Via: [StackOverflow, 49262971/does-phps-file-get-contents-ignore-file-locking](https://stackoverflow.com/questions/49262971/does-phps-file-get-contents-ignore-file-locking)

**Comment by frankdejonge** [comment]
You can use the adapter decorator, or decorate the `FilesystemInterface`, and implement the kind of locking you need. Locking is difficult to standardise and not always supported by the underlying system, but because of the interfaces Flysystem provides you're able to add that yourself, transparently.

**Comment by GDmac** [comment]
Thanks for the reply Frank, I don't understand how on one side (writing the file) you are implementing a LOCK but then not using a LOCK on the read side of things. In the current state of the local adapter you might as well have no locking at all, as its presence suggests some thought on the write would/should be atomic.
