### ISSUE TITLE
Documentation on how to use Config?

### ISSUE THREAD

**Issue by magroski** [thephpleague/flysystem#1042]
### Question

There are no docs available on how to use `Config` (https://github.com/thephpleague/flysystem/blob/master/src/Config.php). What parameters do the array expect?

|    Q        |   A
|------------ | ------
| Version     | 1.0.53

**Comment by on2** [comment]
I have looked into how `Config` works and in the most part it's straightforward and I also defined some options in #1088.

What I couldn't ascertain is a scenario where you'd want to use `setFallback()`. Does anyone have a use case for this?

**Comment by frankdejonge** [comment]
@on2 thats for when you pass config to a method and the global config is used as a fallback when looking up the settings.

**Comment by on2** [comment]
@frankdejonge thanks for the quick reply. I see that in practice here:

https://github.com/thephpleague/flysystem/blob/b2698f33e88ffdf648e06f08fcbe535f20c920de/src/ConfigAwareTrait.php#L44-L45

Would there be an instance when you would define your own fallback when using the library? I can't think of an example which means in terms of documenting `Config` would it be safe to say that you only need to know about it if you're creating your own adapter because in general use you can just pass an array of options to the `Filesystem` constructor?
