### ISSUE TITLE
MultipartUpload

### ISSUE THREAD

**Issue by jasperf** [thephpleague/flysystem#1178]
### Question

How could we do MultipartUpload like is possible for Amazon S3 uploads? See https://docs.aws.amazon.com/AmazonS3/latest/dev/usingHLmpuPHP.html . This to upload files larger than 5MB or at least those large than 100MB. Can we do this with Flysystem as well?

Did read `fopen` will help with large file uploads https://laracasts.com/discuss/channels/laravel/how-to-handle-large-file-uploads-to-s3 . But that is not multi part upload as Amazon S3 SDK provides..

**Comment by jasperf** [comment]
I think I need to be at https://github.com/thephpleague/flysystem-aws-s3-v3 for this.

**Comment by frankdejonge** [comment]
Hi @jasperf, we use the `S3Client::upload` method which internally determines whether or not a multipart upload is needed, so this is handled by the underlying SDK, no need to worry about it from Flysystem's side. Besides that, using streams for large uploads is always recommended since it keeps memory usage low.
