### ISSUE TITLE
Method not deprecated 

### ISSUE THREAD

**Issue by michaelKaefer** [thephpleague/flysystem#1180]
I think the method `League\Flysystem\Filesystem::getAdapter()` should be marked as `@deprecated` in v1 since it is removed in v2. Or am I missing something? Is there an alternative we can use in v2 to get the adapter for a Filesystem in our client code?

**Comment by GrahamCampbell** [comment]
Since v2 is a complete rewrite, I don't think a such a deprecation policy applies?

**Comment by michaelKaefer** [comment]
@GrahamCampbell I saw this: https://github.com/thephpleague/flysystem/issues/1162. That's why it came to my mind. Plus: it would be really helpfull to know if/how we can get the adapter in v2.

**Comment by frankdejonge** [comment]
Hi @michaelKaefer,

When you want access to the adapter, you can use a DI container. Just like you would pass it the adapter, you can reference that internal service as a dependency.

**Comment by frankdejonge** [comment]
I'm ok with adding a deprecation since (although it's a rewrite) it's the next incarnation of the library and version 1 will eventually stop receiving support.

**Comment by michaelKaefer** [comment]
@frankdejonge Thank you a lot, I will do a PR. But to be sure: how can I access for example in Symfony the adapter for a Filesystem service with the ID `default.storage` with DI? I do not need just any adapter but the adapter of the filesystem `default.storage`. Is this possible with DI?

**Comment by frankdejonge** [comment]
@michaelKaefer sorry for the late reply. This should be possible but it might need some adjustments in the bundle, the adapter AND the filesystem it's wrapped in need to be registered as services, this might not be the case.

**Comment by michaelKaefer** [comment]
@frankdejonge Thank you for your answer! I understand it like this: the bundle or the application needs to make all adapters available *and* also needs to know the connection between a filesystem and its corresponding adapter. If I understood correctly it feels like a bad workaround compared to the simple `$fs->getAdapter()`..

**Comment by frankdejonge** [comment]
Hi @michaelKaefer, I understand your sentiment. It is certainly not the first time I've heard it. However, there are a couple of reasons I take this stance. First, it promotes a way of managing dependencies that goes into standard practices and principles, in this case, the dependency inversion principle. This means that Flysystem is now responsible for managing your dependencies. Secondly, since the underlying adapter is should just be an implementation of an adapter, calling any other method breaks the Liskov substitution principle. Lastly, in V1 I've been plagued with arguing about which accessors to allow. When people see this being public, they want other things to be public as well. I have to either give in to all requests, or I have to assess and argue against them all. So for V2, because this costs me a lot of time, I've decided to not support it. Laravel was able to, quite easily I might add, account for this change when upgrading to Flysystem V2. Very little extra code and the dependencies are now explicit.

**Comment by michaelKaefer** [comment]
@frankdejonge Thank you for this detailed and well understandable answer!
