### ISSUE TITLE
ftp_mkdir(): OOPS: malloc error

### ISSUE THREAD

**Issue by moeinpaki** [thephpleague/flysystem#1188]
### Question
Hi there,

I am getting this error on file upload `ftp_mkdir(): OOPS: malloc`, and I can't upload a base64 image on FTP server

**Comment by frankdejonge** [comment]
Hi @moeinpaki,

This is caused by FTP server misconfiguration. Not something we can do from Flysystem's side. There can be a variety of things causing this, selinux being one of them. I suggest you google that error along with your Linux distro and FTP server type for more clues.

In the future, when opening an issue. Please use the issue template and specify the information in the template.
