### ISSUE TITLE
2.0 Question: Exception Naming Convention

### ISSUE THREAD

**Issue by BusterNeece** [thephpleague/flysystem#1204]
I'm looking at the 2.x branch and couldn't help but notice that exceptions in 2.x no longer have the `Exception` suffix, and also share the root namespace with other components, making it more difficult to traverse the library and less obvious what is an exception class and what isn't (unless your IDE highlights the file accordingly).

Is there a reason this change was made? I realize it's often redundant to do this, but I tend to prefer putting exceptions in their own `Exception` folder _and_ including the `Exception` suffix in the class/file name, since other classes using the library will often alias the name down to the base name and it's handy to still have the exception be visible.

If there's no strong reason to do things the current way, I would be happy to submit a PR moving exceptions out of the namespace root and appending the suffix for improved code understandability.

**Comment by frankdejonge** [comment]
Hi, @SlvrEagle23. I prefer to group by concern rather than by type. I try to remove the type suffixes from exceptions because it forces me to write more descriptive names that relate to the intent of the performed action. So it is intentional, and I'm not looking to go back to the exception suffixes (or sub-namespacing). While the exception suffix more easily articulates the type, it conveys very little other information. So in the end this is a preference thing.
