### ISSUE TITLE
First impressions of v2

### ISSUE THREAD

**Issue by stccorp** [thephpleague/flysystem#1242]
Hello,

I just wanted to write about upgrading from v1 to v2.  V1 worked out of the box,  as soon as I upgraded I got

 SSH_AUTH_SOCK errors and 
 Uncaught League\Flysystem\PhpseclibV2\UnableToLoadPrivateKey: Unable to load private key.

I noticed that the example of SftpConnectionProvider  are missing parameters like

      string $privateKey
        string $passphrase

I could not get it to work and unfortunately I dont have too much time to play with the errors.  Maybe they are simple to fix, but just wanted to let you know that I was not able to use it out of the box like version 1

Thank you.  Great software

**Comment by frankdejonge** [comment]
Hi @stccorp,

Thank you for your feedback. In my tests I go over a number of cases with the private key, these are all integration tests. Perhaps you could look at those for the setup. I don't have any other information to go by to help you further. I hope you'll be able to have more time to debug.

Since there's nothing in the issue I can fix, I'll close this. But feel free to comment when/if you have more context.
