### ISSUE TITLE
How do you get the file name from an item in a directory listing?

### ISSUE THREAD

**Issue by opengeek** [thephpleague/flysystem#1251]
### Question

I am trying to get (or filter by) just the file name when iterating over a DirectoryListing, but there does not seem to be any way to get the file name without the full path. Am I missing something or do I have to `explode()` the path and `array_pop()` the file name from the path myself anytime I use a DirectoryListing?

**Comment by EvgenyBarinov** [comment]
+1

It will be very useful to be able to receive `fileName`

I suppose it should be in FileAttributes

**Comment by Nyholm** [comment]
How about using `basename()`?

https://www.php.net/manual/en/function.basename.php

**Comment by Eugentis** [comment]
> How about using `basename()`?
> 
> https://www.php.net/manual/en/function.basename.php

does it works for aws-files?

**Comment by Nyholm** [comment]
It works for all strings looking like a file path

**Comment by frankdejonge** [comment]
In V2 I've not chosen to pre-compute these values because they are often part of a rename method that can just as well incorporate functions like basename as indicated in the comments (this is the correct approach). I'll close this one, if there's another issue do feel free to comment and we can reopen.
