### ISSUE TITLE
removeFunkyWhiteSpace will throw an error with multibyte emojis

### ISSUE THREAD

**Issue by JimKnoxx** [thephpleague/flysystem#1336]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no (I guess)
| Version     | 1.1.4

#### Summary

I noticed that writing a file with an emoji in its name does not work with all emojis.
The method `Util::removeFunkyWhiteSpace($path)` throws an error, if the path contains a multibyte emoji. 
It works fine with "normal" emojis.
The `preg_match('#\p{C}+#u', $path)` does match with the connection bytes in the emoji. 

#### How to reproduce

Create a path with a multibyte emoji, like this one: 🏋🏼‍♀️ and pass it through `Util::removeFunkyWhiteSpace`. It will throw the given "CorruptedPathDetected" error.
For good measure, a path with a normal emoji works, like this one: 😊

#### Side note
After this commit: https://github.com/thephpleague/flysystem/commit/f3ad69181b8afed2c9edf7be5a2918144ff4ea32 the name and description of the method are a bit miss leading. It neither removes stuff nor rejects characters. I would describe it more as verifying the path for having only valid characters.

**Comment by frankdejonge** [comment]
Seems like there's an overlap with the unicode codepoints that can cause a https://en.wikipedia.org/wiki/Time-of-check_to_time-of-use attack. I've tried to look for a regular experession which is less greedy about it, but have failed to find one. Since not using this causes a security concern, this issue cannot be resolved.
