### ISSUE TITLE
Version 3 and PHP8

### ISSUE THREAD

**Issue by m-vo** [thephpleague/flysystem#1405]
Raising the PHP requirement to >8.0 for version 3 does not seem to be necessary in regards of the [changes that were made](https://github.com/thephpleague/flysystem/compare/2.4.0...3.0.0) to support checking for directories. Am I maybe missing something?

Over at [Contao Open Source CMS](https://github.com/contao/contao) we just included Flysystem support in version 2 (not released yet, but it will go into our upcoming LTS). We should really also include support to check for directories as this is a common use case for our users as well. I was happy seeing the release in time, but with also raising the PHP requirement it became unusable for us. :disappointed:

Not sure if we can do something about this, I primarily wanted to leave this as a feedback. Maybe you can consider lowering the requirement again. I see this library as an important tool used across the ecosystem and it would be a pity if this would stop people from migrating or having troubles resolving dependencies.

**Comment by frankdejonge** [comment]
Hi @m-vo,

Laravel and Symfony are upping the requirements for PHP version, which I follow. I would recommend raising your requirement too, _especially_ because it's an LTS. PHP 7.4 is already out of active support, and provided you want to be compatible with other ecosystem parts, it'll be very challenging to keep supporting that requirement.

**Comment by aschempp** [comment]
Our Contao 4.13 LTS is compatible with the Symfony 5.4 LTS, which still supports PHP 7.4.

**Comment by frankdejonge** [comment]
Understood. However, their minimum version doesn't force your minimum.

**Comment by m-vo** [comment]
Thanks for the comments @frankdejonge. We require quite a lot of bundles and our users do so as well. If we would just raise our requirements, it would make it unnecessarily hard to upgrade.

I, as a developer, am an advocate for using latest versions. With Contao this is fine, as we IMHO allow a sensible range of possible dependencies. But in my view, someone building an application on top of our bundles that also includes projects with slower release cycles (or runs on some middle class shared hosting :see_no_evil:), should also be able to update if there are no technical limitations preventing it. 

But it's ultimately up to you, of course.

**Comment by aschempp** [comment]
> However, their minimum version doesn't force your minimum.

You're absolutely right. What I tried to say was that we probably have similar reasons to not require PHP8 as Symfony does in their 5.4 LTS, simply because our users (who are not developers!) need more time to migrate their installations. We have [about 1600 extensions](https://extensions.contao.org) for our CMS and for non-developers a PHP8 requirement might make it impossible to update to the LTS. But our next major version sure will require PHP8, we're following Symfony here as well. Sorry for not being more descriptive 😊

**Comment by WilliamStam** [comment]
the requirement for php 8.0.2 seems to be rather locked in at this point. 

adding ` "league/flysystem": "^3"` to the composer.json file (so im hoping to get the latest v3?

````
"config": {
    "sort-packages": true,
    "optimize-autoloader": true,
    "platform": {
      "php": "8"
    }
  }, 
````

returns an error

```
Problem 1
    - Root composer.json requires league/flysystem ^3 -> satisfiable by league/flysystem[3.0.0, ..., 3.x-dev].
    - league/flysystem[3.0.0, ..., 3.x-dev] require php ^8.0.2 -> your php version (8; overridden via config.platform, actual: 8.0.6) does not satisfy that requirement.
```

im pretty sure there arent any breaking changes for 8.0.2 from 8, might be mistaken. this might catch some people as well.

**Comment by sdwru** [comment]
Requiring v8 is a total dealbreaker for me.  All my backend stuff still only supports v7 and will continue to do so for the forseeeable future.  These are all popular commercial applications I am using on my backend that have existed for many years.  Not some edge case.  Really bad decision imo that relegates this software to experimental for years to come.
