### ISSUE TITLE
SFTP uploads randomly fail with UnableToCreateDirectory exception, when directory already exists

### ISSUE THREAD

**Issue by daanhaitsma** [thephpleague/flysystem#1559]
## Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 3.5.2

### Summary

I am creating a new issue because unfortunately the fix created after https://github.com/thephpleague/flysystem/issues/1557 does not resolve my situation.

Unfortunately in my case it doesn't seem to be a race condition as the directory has sometimes existed for many years already. I was hopeful that the second check you added would still help on this issue as well, so just updated flysystem but unfortunately the same error is still showing up "randomly".

**Do you happen to know of anything else that could cause Flysystem to not detect that the directory exists already?**

---

Just to paint a complete picture, here are the exact calls we make to the Storage disk:
* Have a Laravel SFTP disk:  `$this->disk = Storage::disk('disk-name');`
* Check if file exists: `if ($this->disk->exists($this->filePath)) {`
* Read the stream: `$this->disk->getDriver()->readStream($this->filePath);`
* Combine the existing stream with the new stream, then create or update the file: `$this->disk->put($this->filePath, $content);`

This sometimes succeeds and sometimes fails - with exception `UnableToCreateDirectory` - but after no more than two retries (three total tries) it always eventually succeeds.

---

This issue only came up after updating Laravel and with that Flysystem as well. Previously we were using version 1.0.22 of `league/flysystem-sftp`

**Comment by frankdejonge** [comment]
It could be that this randomness is caused by phpseclib. The adapter has mostly been a 1:1 port of the v1 version where specific capabilities were extracted into separate classes. For example, the connection provider is internal, but does the same. The connectivity check is also the same by default. What is different is the underlying code from phpseclib tho.

What you can do is set the logging for phpseclib to get the actual underlying SFTP instructions, which could give insights into what it's actually doing: https://phpseclib.com/docs/diagnosis#getlog

I wish I could be of more help, but with limited information I can only provide limited guidance.

**Comment by daanhaitsma** [comment]
Alright, I'll continue investigating into phpseclib then. Thanks for your quick responses and pointing me to the log method!

**Comment by daanhaitsma** [comment]
Thanks to this additional logging we found this difference between successful and failed uploads:

* Success: Sends `NET_SSH2_MSG_CHANNEL_OPEN` 1 time, receives `NET_SSH2_MSG_CHANNEL_OPEN_CONFIRMATION` 1 time
* Failed: Sends `NET_SSH2_MSG_CHANNEL_OPEN` 5 times, receives `NET_SSH2_MSG_CHANNEL_OPEN_CONFIRMATION` 4 times

Created a new issue over at phpseclib: https://github.com/phpseclib/phpseclib/issues/1851
