### ISSUE TITLE
Documentation (local, SFTP adapter & Unix visibility) issue

### ISSUE THREAD

**Issue by digiservnet** [thephpleague/flysystem#1661]
### Bug Report

On the Local, SFTP adapter and Unix visibility pages (https://flysystem.thephpleague.com/docs/adapter/local/, https://flysystem.thephpleague.com/docs/adapter/sftp-v2/, https://flysystem.thephpleague.com/docs/adapter/sftp-v3/ & https://flysystem.thephpleague.com/docs/usage/unix-visibility/), the `Advanced usage` section shows about setting permissions, however, these permissions are incorrect (and could become an issue for people not knowing the *nix permissions sytsem).

```php
    // Customize how visibility is converted to unix permissions
    PortableVisibilityConverter::fromArray([
        'file' => [
            'public' => 0640,
            'private' => 0604,
        ],
        'dir' => [
            'public' => 0740,
            'private' => 7604,
        ],
    ]),
```

This would be better with the following permissions:

```php
    // Customize how visibility is converted to unix permissions
    PortableVisibilityConverter::fromArray([
        'file' => [
            'public' => 0644,
            'private' => 0600,
        ],
        'dir' => [
            'public' => 0755,
            'private' => 0700,
        ],
    ]),
```

**Comment by jcogs-design** [comment]
Just want to add that this post was quite helpful - and concur with idea that default values for permissions should be changed to those suggested.

More generally the clarity of documentation about how permissions and visiblity get set in Flysystem really needs some work: the documentation that is there is probably sufficient if you already know what needs to be done, but without sensible examples and elaboration of some imputed terms - for example including an example of code to write a file or create a directory where the `$config` value is used to set permissions would be useful - the documentation does little to help new users of Flysystem.

For example, some explanation of the role and use of the `PortableVisibilityConverter` class - which appears to include default permissions in two different places (constructor and `fromArray`) but when and how one is used rather than the other, how these might be accessed / adjusted to suit other use cases (e.g. writing files that need to be then served by a webserver), and how they interact with the write and create directory methods is unclear.

**Comment by frankdejonge** [comment]
@jcogs-design this is an open source project, send a PR 👍

**Comment by jcogs-design** [comment]
@frankdejonge I would if I even vaguely understood how it works - my limited knowledge comes from spending too much time trawling through stackexchange and elsewhere desperately looking for some clues as how to simply get a directory created on a webserver that will then have permissions to allow users of the site to access the files it contains. Currently I don't have the answers... but should I ever reach that point, and the documentation is still missing, I would of course add the information to the best of my ability to...

**Comment by digiservnet** [comment]
@frankdejonge regarding the original issue (docs), I would happily create a PR for the docs I highlighted, but I couldn't find the documentation for the project as a repo, but if you can point me in the right direction for that, I'd be happy to make a PR for that part at least along with explanations of the permission bits used and why.

A complete indepth guide on Unix permissions is naturally out-of-scope for the docs, but at least the basics for the likes that I put in my OP for public and private permissions if nothing else.

**Comment by frankdejonge** [comment]
@digiservnet the docs are on the gh-pages branch

**Comment by digiservnet** [comment]
> @digiservnet the docs are on the gh-pages branch

🤦🏻‍♂️ thanks mate... I'll get something written up and PR'd for that then 🙂
