### ISSUE TITLE
Problem for big files - PHP Fatal error:  Out of memory 

### ISSUE THREAD

**Issue by ghost** [thephpleague/flysystem#170]
Hello, 

i m using flysystem but i can used it for files with 350 MO i have this error ,

```
PHP Fatal error:  Out of memory (allocated 763101184) (tried to allocate 380559298 bytes) in /var/www/script/vendor/league/flysystem/src/Adapter/Zip.php on line 64

Fatal error: Out of memory (allocated 763101184) (tried to allocate 380559298 bytes) in /var/www/script/vendor/league/flysystem/src/Adapter/Zip.php on line 64

```

what i can do please :

**Comment by fireproofsocks** [comment]
I do not consider this issue closed.  I would encourage the devs here to set as high of standards for their documentation as they set for their code.  Saying "use streams" or "read and write with streams" without providing full examples is not particularly helpful.  The examples that eventually came out in this issue ultimately need to be demonstrated with variations in the official docs.  I'm fairly confident that I'm doing everything here correctly and still PHP crashes with allowed memory size errors.

**Comment by frankdejonge** [comment]
@fireproofsocks while I understand where you're coming from, I don't agree. It's like demanding from the Doctrine project to teach you how to optimise SQL or configure a database server. It's not flysystem's responsibility, it's the developer's. If you have any issues and want me to take a look at it, by all means share some code an I can see how I can help you out. Also, if you have contributions for the documentation, I'd be happy to accept a PR for that.

**Comment by fireproofsocks** [comment]
Regardless of the specific causes of the errors, you need to add the examples to your docs.  I don't think that should require a PR, but if you're having trouble understanding what is unclear then I'm happy to fill your docs with more examples (start with the stream example that was outlined above).  Writing code is easier than writing documentation, and a project is only as good as its documentation.  Re my specific error, I suspect you'd run into similar errors if you ran unit tests while zipping up any medium to large site recursively.  An official example would at least set the record straight as to what's the correct way to do it, and I don't think that strays so far off-topic as optimizing SQL queries etc.

**Comment by saschawiener** [comment]
I came across a similar problem. What I try to do is very basic: Reading a local file and save it to a WebDAV location using the WebDAV adapter. I'm doing it exactly as documented.

`
// Open handle to local file
$fp = fopen('myfile.extension', 'r+');

// Stream to WebDAV
$filesystem->writeStream('foo.ext', $fp);
`

In my scenario, I've chosen a large file which is double the size of my memory_limit in order to make sure I won't be running into memory problems regardless of the file size. However, the memory is exhausted every time, since the script seems to allocate an amount of memory that's equivalent to the file's size. 

In a second, more realistic approach, I used an URL as the file source, which is of course slower. Memory consumption was increasing slower then, but the final result was exhausted memory as well.

Writing to disk instead was no problem. So it seems that as long as the destination is significantly slower than the source, I'm running into that problem. My assumption was to avoid this problem by streaming, because that's what streaming is all about. How can this be solved?

**Comment by saschawiener** [comment]
Sorry, my last comment is not directly related to flysystem. It's an issue coming from the WebDAV plugin, which just doen't implement streaming at all, leading to the Polyfill fallback.

**Comment by frankdejonge** [comment]
@saschawiener from what I remember, the webdav library doesn't support streaming so we can't use it in flysystem.

**Comment by saschawiener** [comment]
@frankdejonge Sabre\DAV\Client actually does accept ressources. See https://github.com/thephpleague/flysystem-webdav/issues/28
