### ISSUE TITLE
No Http Adapter

### ISSUE THREAD

**Issue by basz** [thephpleague/flysystem#253]
Mentioned in the docs/readme yet there is no flysystem / src / Adapter / Http.php

**Comment by danvasquez** [comment]
@frankdejonge any plans to resurrect this? I'd love to have it.

**Comment by frankdejonge** [comment]
@danvasquez there are no concrete plans for me personally, but @reinink has a use-case for it in glide so iirc he's looking into it.

**Comment by reinink** [comment]
Yes, I have plans to create an HTTP adapter, mostly because folks keep asking about it for [Glide](http://glide.thephpleague.com/). No timeline yet though, probably in the next couple months though.

**Comment by twistor** [comment]
I submit https://github.com/twistor/flysystem-http for your consideration. I've adapted it a bit after looking at https://github.com/thephpleague/flysystem/tree/feature/http-guzzle-adapter.

It needs tests and whatnot, but it really is a trivial adapter.

**Comment by reinink** [comment]
Wow, awesome. I'll give this a try. I was hoping to do one that didn't require Guzzle, but instead simply used `file_get_contents()`. Just one less depenency for what is really quite a simple adapter. I'm wondering if Guzzle is really needed? For the `read()` it wouldn't need it, but the `has()` method could be a little more tricky.

**Comment by twistor** [comment]
It would be totally possible to do it guzzle-less. file_get_contents() wouldn't work all the time, since we're doing head requests. But, that's overcomable with some context options to fopen().

Also, we should fallback to doing GET requests on "Method not allow" right?

I'd be happy to switch gears on this a bit. It *should* be possible to to implement an adapter using the regular stream API. The 'http' stream, not pure sockets. (It's possible using pure sockets, but I'm old and tired.)

Strange coincidence, I was just working on https://www.drupal.org/node/2522056 the other day, so I just happen to remember all of the details. 

Conclusion: I'll implement @reinink 's suggestions in my repo, and probably move the Guzzle version to another repo for later discussion.

**Comment by reinink** [comment]
Well, if using Guzzle just makes sense, we can do that. I had just wanted to try and do it without. Whatever you guys think is best.

**Comment by GrahamCampbell** [comment]
> Yes, I have plans to create an HTTP adapter

There was already a PR opened here, but @frankdejonge decided he didn't want it in the end.

**Comment by GrahamCampbell** [comment]
https://github.com/thephpleague/flysystem/pull/178
https://github.com/thephpleague/flysystem/pull/244
https://github.com/thephpleague/flysystem/pull/286
https://github.com/thephpleague/flysystem/pull/363

**Comment by frankdejonge** [comment]
@GrahamCampbell it's not that I didn't want it, when this was going on iirc we were working towards a 1.0 release, spilling things up and this never got to a point where it fit in the new setup. I've talked to @reinink about this, and he'll get this to a point where it _can_ get in.

**Comment by GrahamCampbell** [comment]
:)

**Comment by reinink** [comment]
Cool!

Unrelated: @GrahamCampbell I voted for ya buddy, hope you win! ;)

**Comment by reinink** [comment]
But seriously, should we just use Guzzle? To me I was avoiding it because it's an extra dependency that could potentially conflict with other versions. Mind you, the version constraints could probably be super relaxed, given we'd be using like two methods. Well, that's assuming those methods haven't changed much over through the different versions. What do you think?

**Comment by GrahamCampbell** [comment]
> I voted for ya buddy, hope you win! ;)

Thanks. :)

> But seriously, should we just use Guzzle?

Provided we support both guzzle 5 and guzzle 6, there should be no issue. I think both versions will be maintained for 2 years and there are no plans for a guzzle 7 release as far as I know.
