### ISSUE TITLE
Stream wrapper

### ISSUE THREAD

**Issue by piotrantosik** [thephpleague/flysystem#318]
Hi!

Thanks for amazing script!
Do you plan to introduce support for php wrappers, eg. flysystem://file_system_mount_point using stream_wrapper_register?

**Comment by twistor** [comment]
https://github.com/twistor/flysystem-stream-wrapper/

As a note, I've whipped this up. You can declare arbitrary stream protocols. There is quite a bit of over head. I have some thoughts on optimization. I only implemented it because it's needed for Drupal's stream API. I just broke the stream wrapper part out today since it seemed somewhat useful.

@frankdejonge I could make a PR or leave it as a separate project. I don't care much either way.
