### ISSUE TITLE
Async sync strategies

### ISSUE THREAD

**Issue by ltouro** [thephpleague/flysystem#387]
Hello,

This question was initially posted thephpleague/flysystem-eventable-filesystem#4 which I think is the wrong place (maybe this is the wrong place as well? :confounded:).

I have the following scenario: Several front-end web servers serving a web app, each one having a local filesystem, to where user uploads are placed temporarily. An external storage, in which is applied sync strategies from the different local filesystems, in order to ensure that external storage has all files uplodaded by users.

It is desirable that front-end servers write files on the local fileserver on synchronous fashion but writes the file to the external storage on asynchronous fashion (user should not wait for this process to finish).

I was wondering the best path to achieve this sync scenario: Eventable Filesystem allow me to hook events on after-write of files for different local filesystems but i'm not sure how it would work. I'm afraid that these events are triggered in synchronous fashion and I dont wan't to make the user to wait for these sync events to complete.

I'm also have some application servers that run workers to do jobs throught supervisord like service.
The sync strategy could be a job itself but how workers (in app server) would know about each front-end filesystem access endpoint? The front-end webservers may have horizontal scalling configured. Thus, I dont know in advance how many front end server will be running at given time.

Running the worker/job on each front-end is not an option due to shell access restrictions which prevents running workers reliably.

Is this package suitable for this use-case? Does anyone have any tips to this kind of use-case? I'm doing something wrong (besides my poor english)? Any comments are welcome.

**Comment by frankdejonge** [comment]
@ltouro Hi,

This is not really an issue that any filesystem abstraction can easily fix for you. Most of the things you describe here, are business decisions. If the remote upload is really something you want to steer clear from, you could also think about creating a job queue per worker which only handles it's own uploads to the "master" filesystem. So when a use uploads, you store it locally. The instance puts a job on it's own queue (like, user-uploads-3 for the third instance), and only listen to that queue. You'll have to take this into account with your scaling needs too. When downscaling, you must be absolutely sure that all the local files have been uploaded to the master before shutting it down and removing it. This can create complexity, a lot of it actually. My advice would be to see if it's really that bad for the response times to upload it in the same call. Or adapt the UI so an upload can start before the form is actually submitted. This way the upload can be done directly on the master, which not blocking the UI.

Since this is  not really an issue with the package, I'll close it. Feel free to send follow up question in this thread. Another suggestion would be to move this question to StackOverflow instead.

**Comment by ltouro** [comment]
@frankdejonge Hi Frank, 

Thank you very much for your thoughts on this matter. I liked the idea of having the UI uploading the files to a central filesystem before the form being submited. The downside is to have yet another server to handle uploads and serve uploaded files.

I will check what would be the latency of uploading the files to a separate FTP server on the same request. Maybe the increase on response time does not justify adding such complexity. Thank you once again :+1:
