### ISSUE TITLE
Consider adding AbstractAdapter::getPathPrefix() to AdapterInterface

### ISSUE THREAD

**Issue by df-jablan** [thephpleague/flysystem#422]
I've noticed that all of final adapters (that I've looked at) appear to descend from `AbstractAdapter`. I like the idea of having a base class with which to work. And also understand the urge to fill it with stubs (or not). 

However, since the only way to retrieve the path of an existing adapter is via the `AbstractAdapter::getPathPrefix()` method, it, `getPathPrefix()`, should be in `AdapterInterface`. 

If I'm way off mark, just give me the back of your hand. ;)

**Comment by frankdejonge** [comment]
I didn't add this to the interface because there can also be adapters which don't use a path prefix. Adding this to the interface explicitly would force adapters to check wether it's set and throw an exception otherwise. This because you do not want to silently ignore these settings. I hope this makes sense for you?

**Comment by df-jablan** [comment]
Sure that makes total sense. My dilemma was that I need the full **real** path of where that Filesystem lives. I know the object knows where it lives, but it won't tell me. I can calculate it from the adapter's prefix, but have no guaranteed way via interface. That's all. :(
