### ISSUE TITLE
normalizePath removes '/' on beginning of path

### ISSUE THREAD

**Issue by leberknecht** [thephpleague/flysystem#462]
Due to 
```
$normalized = preg_replace('#/{2,}#', '/', trim($normalized, '/'));
```
a file with a path like `/tmp/whatever.pdf` will be normalized to `tmp/whatever.pdf` and read will fail.

**Comment by frankdejonge** [comment]
@leberknecht this is correct. All paths in flysystem are relative. Each adapter is aware of a root, so is the Local adapter. You can set the root to `/` if you prefer that, in which case this will work again.

**Comment by leberknecht** [comment]
Ah! Missed that! Thanks!

**Comment by frankdejonge** [comment]
@leberknecht no problem at all :) Since you didn't know about this:

The reason why Flysystem's paths are relative, is that it makes ever usage of flysystem very easily portable within or across filesystems. While your files might be in /var/www/user-uploads in your local folder, when you then move to S3 you don't want to have to replace all the paths across your application. Relative paths make sure you don't have to do at that time. In a way it's a "thank me later" feature, or best practice rather.
