### ISSUE TITLE
Fatal Error SplFileInfo::getType(): Lstat failed if Directory or file is not readable.

### ISSUE THREAD

**Issue by sukrit-adhikari** [thephpleague/flysystem#472]
In adapter League\Flysystem\Adapter\Local if the function normalizeFileInfo(SplFileInfo $file) is called and $file is unreadable due to permission issue then 'SplFileInfo::getType(): Lstat failed' Fatal Error is thrown.we can simply correct it by checking if the file is readable by ::

introducing a try catch block 

or

if(!$file->isReadable()){
// do Something that avoids this fatal error
//Or throw an exception which can be managed
}

**Comment by sebastiansulinski** [comment]
+1 - same problem here

**Comment by JarJak** [comment]
Why closed?

**Comment by dvcsiky** [comment]
> Why closed?

I answer this because it wasn't immediately apparent to me either. :smile: 

Whilst there were no references to this issue anywhere, including the commit / any PR, and it was seemingly included within a "Coding Standards fix" commit, ***it was supposedly fixed*** with the linked commit in the closing notice.

Please check that commit, as well as remember that `closed this in %x` is supposed to mean `fixed`. (I will. :laughing: hopefully)

_OTOH, I am still getting `lstat failed` issues, which are thus most probably not permission-related; will have to investigate further._

**Comment by Uili-Simteau** [comment]
Same issue here
