### ISSUE TITLE
Symlinks aren't handled correctly

### ISSUE THREAD

**Issue by TrafeX** [thephpleague/flysystem#474]
Hi,

I'm running into an issue with symlinks to files.
When I call the `Filesystem::get()` method on a symlink that points to a file, it returns an instance of `Directory`.
This happens because the type is not `file`, but `link`:
https://github.com/thephpleague/flysystem/blob/master/src/Filesystem.php#L499

Maybe it's possible to check if it's a link, get the resolved path/realpath and return the type of that in the Local adapter?
https://github.com/thephpleague/flysystem/blob/master/src/Adapter/Local.php#L339

**Comment by frankdejonge** [comment]
A fix has been pushed to make symlinks explicitly unsupported. This is done because they can't be handled without forcing a particular strategy upon the user. Flysystem respects a root, symlinks are possible leaks. A resolved symlink could be outside of the defined root. In that case Flysystem can't handle it, but can't ignore it either. If a symlink is used to keep files outside of a webroot (accessible to the public) a symlinks should be placed on the root directory of the adapter. This _is_ supported.
