### ISSUE TITLE
Symlinks trip up local adapter when deleting directory

### ISSUE THREAD

**Issue by franzliedke** [thephpleague/flysystem#502]
When removing a directory recursively with `deleteDir()` that contains a symlink, [things fail](https://github.com/franzliedke/studio/issues/23).

Seems to be caused by [this line](https://github.com/thephpleague/flysystem/blob/3b1077f6f4dd04b974fc9479660f6681942db687/src/Adapter/Local.php#L329).

I'm a little confused, though - shouldn't this have caused [this exception](https://github.com/thephpleague/flysystem/blob/3b1077f6f4dd04b974fc9479660f6681942db687/src/Adapter/Local.php#L349) to be thrown in the first place?

**Comment by frankdejonge** [comment]
@franzliedke, that's correct. The exception (a more clear one than a fatal error) was added in the latest path release. Symlinks are explicitly not supported. Would you happen to know why a symlink was added there in the first place? Since you're using flysystem, my guess symlinks wouldn't be used, right?

**Comment by corbosman** [comment]
I reported the bug. I use his package studio to develop laravel5 packages before moving them to packagist. Some composer dependencies like phpspec add a vendor/bin/phpspec symlink, so when he wants to delete the studio package, it encounters the symlinks which then fails.

**Comment by franzliedke** [comment]
Yep, it's a Composer-generated directory.

@frankdejonge Can you expand on why deleting symlinks is not supported?

**Comment by frankdejonge** [comment]
@franzliedke symlinks are not supported because they're a leak from the root. A symlink could refer to a file outside of the root. Also, it's hard or sometimes impossible to determine what action to take. For instance, a `delete` action, would it delete the symlink or the linked file? Flysystem's main objective is to facilitate filesystems as storage units. So the local adapter is actually tackled in the same manner a filesystem on S3 or cloudFiles would be. Does that clear it up? Perhaps, since all is local and it's not content but source files, in this case it woud be better to go with the symfony/filesystem package instead? Another possibility would be to not use flysystem for this particular action.

**Comment by franzliedke** [comment]
Cool, thanks for clarifying. I'd think, though, that if you want to delete a directory, you simply want all symlinks (not the targets) within it removed. Have you experienced (or heard of) any use cases where the opposite is true?

Thanks for the suggestion, I will switch to Symfony's lib, I really don't need the abstraction offered by Flysystem. Superb package, though!

**Comment by frankdejonge** [comment]
@franzliedke I'm not a symlink guy myself. But my "advisors" have warned me about this. In this case I think the symfony lib is indeed a better match.

**Comment by franzliedke** [comment]
Cool.
