### ISSUE TITLE
filter criteria

### ISSUE THREAD

**Issue by kanariezwart** [thephpleague/flysystem#503]
First, thanks and props for this awesome library. :bow: 
When calling `listContents` it should always return all contents by default. Makes sense. 
Is there a way of finding files by filter? Is this functionality already present and did I fail to find it? I created a simple plugin to filter based on regex, and that got me thinking to create a filter plugin that can filter the content list by multiple criteria:

Say I want to find/filter all entries that match a certain type, base name, filesize.

``` php
$criteria[] = ['basename' => '*something*']; // simple filter on base name
$criteria[] = ['basename' => ['regex' => '/bla_.*/']]; // regex like filter
$criteria[] = ['extension' => '.txt']; // filter on file type or mime type
$criteria[] = ['size' => '< 1024' ];  // filter on size

// fetch only entries that match filter
$contents = $filesystem->listContentsBy($criteria) ?
```

Would there be any appreciation for such a plug-in? Or is this beyond the scope of Flysystem?
Any thoughts?

**Comment by barryvdh** [comment]
Something like the [Symfony Finder](https://github.com/symfony/Finder) perhaps, a fluent interface?

`$filesystem->finder()->name('photos*')->size('< 100K')->date('since 1 hour ago')->in('/media');`

**Comment by kanariezwart** [comment]
@barryvdh a finder plugin like symfony finder, sounds like a great start. I'll have a look.  :+1:

**Comment by frankdejonge** [comment]
Hi all, I'd say a package which relies on flysystem would be the way to do. I don't see flysystem ship with this itself since the majority of the adapters can't support, leading to segmented feature coverage (which is what I want to avoid). The way to go would be to decorate the response, manipulate the output from the listContents call. Because it's a decoration it would be relatively easy to supply it as a companion package instead of in the main package. If you guys have any objections or feel like I'm way off in this conclusion, let me know and we can discuss.

**Comment by barryvdh** [comment]
Why wouldn't most adapters not support it? Only downside would that the filtering would ofcourse be _after_ the contents are fetched, but most adapters support timestamps/size right? So it would basically provide filtering after the listContents() result.

**Comment by frankdejonge** [comment]
@barryvdh as you stated, it would probably be a "post listing" operation. Mapping all those criteria's to actual listing calls sounds pretty magical to me. Though if you have idea's how to implement this, I'm very much open to suggestions.

**Comment by barryvdh** [comment]
@frankdejonge Sorry, bit confused. Are you open to suggestions for 'post listing' or to 'magical calls'? Or both?

**Comment by frankdejonge** [comment]
@barryvdh I was referring to converting this expression-like syntax to actual listing calls on the adapters.

**Comment by kanariezwart** [comment]
>  don't see flysystem ship with this itself since the majority of the adapters can't support, leading to segmented feature coverage

@frankdejonge thanks for feedback. Makes sense not all of them support all the metadata details.
Perhaps each adapters could return what metadata features it supports?

A finder/filter plugin can pick up on what it criteria it can actually filter on. This of course will lead unexpected behaviour when querying different adapters.

**Comment by yellow1912** [comment]
I think:
1. We can pass the filters to the adapter, if it supports them then it can filter and let us know in the result that filters are already used. This will allows us to filter much faster with adapters that support filters.
2. If the results are not filters, we can do in the post listing phase
3. If not all filters were able to be applied, we could throw exception since the result may not be what the users expect

**Comment by kanariezwart** [comment]
I like @yellow1912  idea :+1:

**Comment by daryush** [comment]
I've created a proposal based on rules from @yellow1912 comment. Waiting for comments at #689

**Comment by DarkSide666** [comment]
So how this go? Will it be possible to filter files at some point in near future? :)

**Comment by frankdejonge** [comment]
I don't want to support filtering because the only reliable way would be either an over-engineered masterpiece, or a too generic solution that would not make this a 80/20 solution.
