### ISSUE TITLE
Methods return boolean?

### ISSUE THREAD

**Issue by fbm-static** [thephpleague/flysystem#509]
Hello,

For example at:

https://github.com/thephpleague/flysystem/blob/master/src/Filesystem.php#L99
https://github.com/thephpleague/flysystem-aws-s3-v2/blob/master/src/AwsS3Adapter.php#L153

How will I get the result of the creation? If I need to get the ID of the object created. It's supposed to return the file's metadata as an array but the Filesystem will return it as a boolean.

Thanks.

**Comment by frankdejonge** [comment]
@fbm-static Hi, all the write methods (write, update, w/ or w/o streams) return a success boolean, the metadata from from the adapter is returned because of cashing purposes with the `league/flysystem-cached-adapter` package. I'd are not a concept Flysystem concerns itself with. If you explicitly need the ID, it seems your use-case is different from Flysystem's, you might be better off not using flysystem in this case. Is there anything in particular you'd like to do with that id?

**Comment by fbm-static** [comment]
Thanks.
