### ISSUE TITLE
Get MD5 checksum of remote files on Amazon S3 and Rackspace Cloudfiles

### ISSUE THREAD

**Issue by hi2u** [thephpleague/flysystem#521]
I haven't been able to find anything about checksums or MD5 related to Flysystem.

Is there a way to get the MD5 checksum of a remote file on Amazon S3 and Rackspace Cloudfiles?

They both support getting the MD5 checksum using their APIs (without downloading the file).

**Comment by foaly-nr1** [comment]
+1

**Comment by divdax** [comment]
+1

**Comment by GrahamCampbell** [comment]
:+1: Can be implemented for other drivers by streaming the file I guess.

**Comment by basz** [comment]
private function getS3Metadata(AwsS3Adapter $adapter, $path): string
    {
        // getting etag data
        $result = $adapter->getClient()->getObject(
            [
                'Bucket' => $adapter->getBucket(),
                'Key'    => $adapter->getPathPrefix() . $path
            ]
        );

        return trim($result['@metadata']['headers']['etag'], '"');
    }

**Comment by foaly-nr1** [comment]
That's what I was using @basz, but from 10M filesize on it's not actually correct anymore.

**Comment by basz** [comment]
If you are referring to the fact that S3 calculates different etag from multipart upload I agree. By default that seems to be for files larger then 5Mb. I have not found how I can change that setting with FlySystem. @frankdejonge would you know if it is possible to configure the S3 adapter differently?

https://github.com/aws/aws-sdk-php/blob/master/src/S3/MultipartUploader.php#L43-L44

To calculate the hash like aws does it the [script](https://gist.githubusercontent.com/emersonf/7413337/raw/16f7b7ae3544e1aaba007fad9c556c8fa13dff81/s3etag.sh) mentioned [here](https://www.savjee.be/2015/10/Verifying-Amazon-S3-multi-part-uploads-with-ETag-hash/) help, but only if you have the file locally.

I am trying to compare the hashes of two files in different buckets in order to determine if they need to be synced. This is problematic if the etag/hash might be different while the actual binary data is the same.

**Comment by metamaker** [comment]
+1, would boost significantly performance of file comparisons

**Comment by reppair** [comment]
I could use this too (or some advise), I am trying to actually figure out if this type of check is done after downloading a large file from S3 or after uploading one to S3. Should I implement this type of check manually to confirm that the downloaded file is the same as the one on S3? Also for uploading I see I can forward my own metadata as explained [here](https://stackoverflow.com/a/37679830/7164760) and compare that manually after the upload is finished. Is this a thing I need to worry about or if I do not get an exception that something failed I can consider the files to be the same?

**Comment by papppeter** [comment]
hi @reppair 
i did found a workaround, but i think it is not really the best solution:
if you check the code below. you can see FileAttributes, which holds information aws s3 ETAG -> which is a file hash

FilesystemReader::listContents
```
try {
    $listing = $filesystem->listContents($path, $recursive);

    /** @var \League\Flysystem\StorageAttributes $item */
    foreach ($listing as $item) {
        $path = $item->path();

        if ($item instanceof \League\Flysystem\FileAttributes) {
            // handle the file
        } elseif ($item instanceof \League\Flysystem\DirectoryAttributes) {
            // handle the directory
        }
    }
} catch (FilesystemError $exception) {
    // handle the error
}
```

there would be a great need for a md5 checksum!

**Comment by reppair** [comment]
> i did found a workaround, but i think it is not really the best solution:
> if you check the code below. you can see FileAttributes, which holds information aws s3 ETAG -> which is a file hash

The Etag is easy to get, the problem is that it is not always the `md5` hash of the file, if it is multipart upload, then it is a `md5` of the concatenated `md5` hashes of each part.

**Comment by papppeter** [comment]
@reppair 
thanks for mentioning. I just encountered this problem.

my quick and maybe dirty workaround is for now:
md5(fileSize + lastModified + basename)

i think most of the time it should work.
