### ISSUE TITLE
[Security] Local file system doesn't enforce path

### ISSUE THREAD

**Issue by aimeos** [thephpleague/flysystem#576]
The local file system adapter doesn't check if the path contains '../' so it's possible to read/write to a path outside the file system defined by the local adapter. As links are considered evil, this should be checked too, e.g.:

```
$root = realpath($root);
if(strncmp($root, realpath($root . $path), strlen($root)) !== 0) {
    throw new Exception('bad path');
}
```

**Comment by frankdejonge** [comment]
Although I see your concern, this would stretch the reach of flysystem a bit too far. Having the root definable as a relative path (instead of requiring it to be absolute always) seems a bit too strict. It's an easy check to make before constructing a flysystem local adapter instance, and there are many cases where local relative root paths are the norm, especially for non-public folders.

**Comment by aimeos** [comment]
Relative paths for the root path and inside the flysystem file system might be OK as long as it doesn't lead to situations where you can read/write (accidentally) outside of the root path.

**Comment by frankdejonge** [comment]
This is actually guarded within the `Util::normalizePath` utility function. It resolves relative paths and when it breaks out it throws an exception.
