### ISSUE TITLE
use a FileInfo (or MetaData) class instead of plain array

### ISSUE THREAD

**Issue by bvarent** [thephpleague/flysystem#635]
I would love if `FilesystemInterface#listContents` and `#getMetadata` returned (an array of) an instance of some t.b.d. FileInfo class. Instead of an array key/value pairs, like now. The reasons are obvious I think. [Here](http://www.brandonsavage.net/stop-returning-arrays-use-objects-instead/) is an article elaborating on the subject.

Concerning BC. The supposed FileInfo class could implement ArrayAccess, Traversable and Countable to keep it usable as if it was an array. I do see a possible issue when the array is used elsewhere as an argument for a parameter type-hinted with `array`.

I would be happy to implement this myself, if we agree on the usefulness and sanity.

**Comment by deviantintegral** [comment]
This would be a very nice improvement. As-is, the code is a bit confusing as far as adapter implementations go.

For example, `\League\Flysystem\ReadInterface` defines a few methods for metadata, and they all return arrays. When I saw that `getTimestamp()` returned an array, I went to the docs to find out what the array keys are - and it turns out in some adapters (S3 and Local) they just wrap and return getMetadata(). But since we don't define what keys are returned, adapters could return arbitrary or conflicting values for all of the get methods. If an adapter had a 'visibility' key, that would clobber 'visibility' as used in the caching adapter.

**Comment by johndodev** [comment]
Implementing an adapter is a nightmare. We have to look the code of the interface, code of some of already existing adapter, code of Filesystem.php, some doc in the website, then MAYBE you can approximatively understand what you have to do.

For example, the read function in ReadInterface should return an array. What array ? So, we look at Filesystem.php, the read function return the "contents" key. What else should we know ?

Please do something..

**Comment by frankdejonge** [comment]
@johndodev there's actually docs about this here: http://flysystem.thephpleague.com/creating-an-adapter/

**Comment by frankdejonge** [comment]
@johndodev also, "it's a nightmare" is not really a great motivator, especially when you only come with complains, not suggestions or solutions.

**Comment by kalpaitch** [comment]
This is an example of an issue resulted in inconsistent keys returned by different adapters - 
 - https://www.drupal.org/project/flysystem/issues/2955174#comment-12539370

I'm sure there are more issues to be uncovered, but I think having a consistent interface returned would resolve these issues nicely. Either that or we'll need to go round checking that all adapters are returning valid values.

**Comment by frankdejonge** [comment]
@kalpaitch the metadata is a best-effort operation. If the _require_ certain information use the specific accessors.

**Comment by kalpaitch** [comment]
Wow that was quick :) True... but looking at `$this->permissions[$metadata['type']][$metadata['visibility']]` that line definitely assumes that metadata is more than a best-effort.

**Comment by frankdejonge** [comment]
All the return info for any type of metadata is in array form from the adapters to leverage all the returned information, this make it possible to do extensive caching which is a huge bonus for filesystem operations. So with any given call that returns some sort of metadata we convert everything we get back because it's a little expense for a huge gain potentially.
