### ISSUE TITLE
listPaths and listWith not found

### ISSUE THREAD

**Issue by kamov** [thephpleague/flysystem#638]
hi,
the method listPaths() seem not exisintg on Filesystem library, I found this on API page.
Call to undefined method League\Flysystem\Filesystem::listPaths
The same for listWith()
Call to undefined method League\Flysystem\Filesystem::listWith

**Comment by frankdejonge** [comment]
@kamov Hi, this is addable through a plug in, the `ListPaths` plugin, which you can add by calling `$filesystem->addPlugin(new ListPaths());`.

**Comment by kamov** [comment]
I got it, thanks!

**Comment by mindplay-dk** [comment]
Why is this a plugin?

It's documented statically, implying you can expect it to exist, so it's pretty surprising to have to learn about this error by way of a github issue.

I'd suggest moving this functionality to the file-system abstraction itself, because the plug-in approach breaks LSP: I can write a class that depends on `FilesystemInterface`, but currently you can't safely depend on any of the built-in plug-in features.

There is no initialization cost for any of the built-in plug-ins - loading this bit of functionality (and most other built-in plug-ins) would be effectively zero overhead.

**Comment by frankdejonge** [comment]
@mindplay-dk the plugin system is a tradeoff. We keep the public interface smaller, still provide it and if you need to rely on it you can still either extend and call the plugin internally, or recreate the functionality in some sort of wrapper and then the plugin serves as an implementation reference. In short, these plugins allow is to "ship" these operations without polluting the base functionality.
