### ISSUE TITLE
MountManager::filterPrefix bug introduced in PR #651

### ISSUE THREAD

**Issue by janhartigan** [thephpleague/flysystem#664]
Pull request #651 introduced a fairly nasty bug that strips content from files that contain `://`. The issue was discussed in that PR to the extent of my knowledge of how the mount manager does its work. There doesn't seem to be an immediately obvious resolution to the issue, otherwise I would have created a PR myself. Please let me know if you have any questions or need anything from me beyond what was discussed in #651.

Thanks!

@sdsomma

**Comment by frankdejonge** [comment]
@janhartigan could you check if the problem still exists on current master. I believe I fixed it after the regression was spotted, we may need to tag that version still.

**Comment by janhartigan** [comment]
@frankdejonge thanks it seems to be fixed. Out of curiosity, is the issue that was presented in #650 / #651 still around? I never had the problem myself since I don't use that mount manager syntax, but @afroewis might be interested to know.

**Comment by frankdejonge** [comment]
@jacekbarecki sort of, it wasn't really a bug. The `rename` method for the mount manager was originally created to do `per` filesystem renamed, so in filesystem X with path Y put it in path Z. The `move` method is there to do pretty much the same thing but gracefully handle cross filesystem moves. Since a rename in PHP is effectively a move, that should be used.

**Comment by frankdejonge** [comment]
@janhartigan I've tagged 1.0.23 which should be available on packagist shortly.

**Comment by janhartigan** [comment]
@frankdejonge sweet thanks for the info!
