### ISSUE TITLE
Did you just drop php5.4 & php5.5 in a patch version?

### ISSUE THREAD

**Issue by gsdevme** [thephpleague/flysystem#711]
Did you just drop php5.4 & php5.5 in a patch version? 
Also looks to be missing from the changelog....

https://github.com/thephpleague/flysystem/compare/1.0.28...1.0.29

`PATCH version when you make backwards-compatible bug fixes.` 
http://semver.org/

**Comment by frankdejonge** [comment]
Yes, those version are end of life, it's not an interface thing. I'm not going to support end of life versions forever. I'll add it to the changelog.

**Comment by gsdevme** [comment]
I totally agree they are EOL, but they didn't just go EOL overnight.. given you had been supporting them its a shame you just pulled the plug with a patch version and without a changelog to even explain it. 

I agree its not an 'interface thing' but packages using this package are likely to be locked to a similar 5.4/5.5 so you have at least broken it for those packages also. 

Laravel **PHP 5.5**
https://github.com/GrahamCampbell/Laravel-Flysystem/blob/master/composer.json#L13

Symfony **PHP 5.4**
https://github.com/1up-lab/OneupFlysystemBundle/blob/master/composer.json#L18

Zend **PHP 5.5**
https://github.com/bushbaby/BsbFlysystem/blob/master/composer.json#L13

**Comment by frankdejonge** [comment]
Thos packages still work with the older versions, so they're not broken.

**Comment by gsdevme** [comment]
@frankdejonge thats not true look at the Symfony package and its composer configuration `"league/flysystem": "^1.0.14"` <-- this will pull the latest `1.0` which includes this drop for php5.5

**Comment by frankdejonge** [comment]
That should resolve to 1.0.28 then.

**Comment by gsdevme** [comment]
Well is that the correct answer? or should a PHP version drop not be a *PATCH* but a breaking change.

**Comment by frankdejonge** [comment]
What do you mean with "is that the correct answer"?

**Comment by frankdejonge** [comment]
But dependency changes, including platform ones are not a change in public API. In SemVer you version that, so this should be OK in a patch version even.

**Comment by frankdejonge** [comment]
But, @gsdevme, are you running on PHP < 5.6?

**Comment by gsdevme** [comment]
This package publicly stated it worked with PHP 5.4, and then people built symfony, zend and laravel packages based on that.

You then took the carpet from under their feet without any method to prevent this unless all packages had hardcoded 1.0.28 into it (I mean why would someone do this anyway!)

Im not against dropping the support, sadly yes 1x server has php55 and is very much due an upgrade but its not publicly facing thankfully just I haven't had the time to upgrade although thankfully its going to happen this week.

I think we will just have to agree to disagree that just changing the supported PHP version is acceptable in a patch release. I will make a note that all League packages need to be fixed to exact versions vs `~` perhaps as they might change PHP versions at random times.

**Comment by frankdejonge** [comment]
I've lowered the minimum php version to 5.5.9 to have parity with symfony and the likes. A word of advice though, @gsdevme; If you want people to cooperate, perhaps think about how you raise issues. A "did you just do X" issue is not very friendly. I maintain open source projects not because people are entitled to it, but because I find joy in sharing code.

**Comment by gsdevme** [comment]
Sure, I'm in agreement with you. Stressful day at the office. Apologies.

**Comment by barryvdh** [comment]
Composer is smart enough to resolve the latest compatible version. If your project is PHP5.4 (or you define your platform config in composer.json to be PHP 5.4), it will resolve to the latest version that supports PHP 5.4. So `^1.0.14` could resolve to `1.0.28` in your php 5.4 project and `1.0.30` in php 5.5.

I'm in favor of dropping PHP 5.4 support, but perhaps this would be better fit as a minor version, instead of patch? That way it would be easier to provide a security fix if needed (eg. tag a new 1.0.31 for 5.4, while the usual development is in 1.1). (Perhaps for the next bump ;))

**Comment by gsdevme** [comment]
Yeah, the platform in the composer is the solution we went for.
