### ISSUE TITLE
FTP download - double file write on local drive

### ISSUE THREAD

**Issue by skrivy** [thephpleague/flysystem#719]
In order to download let's say 10G file, I have to use readStream method as simple read would consume enormous amount of memory.

When using readStream, the file is first downloaded to a temporary file created in your sys_get_tmp_path(); You should then copy content of the temp file to the destination path - e.g.:

```
        $fp = fopen($destination, 'w');
        $stream = $storage->readStream($path);
        stream_copy_to_stream($stream, $fp);
        fclose($fp);
```

However, this means that file is copied 2 times:
1. Copy from FTP to temp file
2. Copy from temp file to your destination file

Is there any way to optimize this behavior? I tried to find a way to get path from $stream, but I couldn't find any function providing such information.

**Comment by bradbforbes** [comment]
Hey there! This may not directly solve your problem, but just some points to consider:

1) The file shouldn't be copied twice by the server, since moving the file to a new path on the same file system won't require it to actually copy again and should be nearly instantaneous.
2) There are good reasons to use a temporary folder as a staging area for this task, especially in cases of large files, such as automatic cleanup of failed attempts, isolating corrupted attempts from your application, and keeping your application from attempting to read an incomplete file.
3) Both read() and readStream() use streaming and a temporary folder, and there doesn't look to be any alternatives available.

**Comment by twistor** [comment]
This might be possible using `ftp_exec()` to execute a direct copy on the server.

**Comment by frankdejonge** [comment]
This is out of scope for flysystem because we're tied to whatever PHP provides.
