### ISSUE TITLE
Reflected XSS vulnerability

### ISSUE THREAD

**Issue by cyberpunksec** [thephpleague/flysystem#730]
Hi there,

I was performing a quick security review on the OctoberCMS software when I came across a reflected Cross Site Scripting vulnerability.  The issue seems to be affecting the flysystem software which is why I have raised the issue here.

The vulnerability seems to affect the 500 page.  
![reflected_xss](https://cloud.githubusercontent.com/assets/12884550/20464799/8c5f9410-af46-11e6-9c82-33747aee160d.png)

Unfortunately, I've not been able to invest any time into create a patch for you guys.  Hope the screenshot is enough for the team to recreate and produce a patch.

Cheers :)
David

**Comment by frankdejonge** [comment]
@cyberpunksec I can't delete this :(

**Comment by frankdejonge** [comment]
Also, I believe this is actually a security issue for @octobercms rather than flysystem. In any production environment exceptions like this should never be displayed. So october cms needs to adjust some configuration for this.

**Comment by cyberpunksec** [comment]
Thanks for the fast response @frankdejonge I'll contact them :)

However, is this still not a flysystem problem?  I mean sure a production system should have exceptions turned off but if they don't they'll be vulnerable because of the flysystem software right?

**Comment by frankdejonge** [comment]
@cyberpunksec it's outside of Flysystem's responsibility to account for log/exception output. This is an responsibility at the application level. This should be handled at the logging level and in logging display mechanisms. Otherwise EVERY package out there which has user input in their exceptions should have an escaping mechanism. Which is not a workable situation. Similarly, when PHP throws exceptions where you get user input back, it doesn't escape this for you either. So by that definition PHP would be vulnerable to XSS attacks to, but that's not really how it works.

**Comment by cyberpunksec** [comment]
I see, cheers @frankdejonge I'll be sure to push this over to @octobercms 👍

**Comment by frankdejonge** [comment]
@cyberpunksec no worries! Thank you for helping out 👍
