### ISSUE TITLE
How can I copy a file from one bucket to another?

### ISSUE THREAD

**Issue by CitizenBeta** [thephpleague/flysystem#742]
I'd rather not have to download a file and upload it again to move it from one bucket to another. But, it appears that the move() method only allows within a single bucket. Is there another way to accomplish this?

**Comment by frankdejonge** [comment]
@CitizenBeta there's no way to do this directly in flysystem. Although you could extend the AwsS3V3 adapter to allow it to be used as a multi bucket adapter. This is not the default use-case, mostly because it would require bucket name prefixing in any call which harms portability, but it is definitely possible. On the other hand, such operations are quite specialised so either using the AWS SDK directly or wrapping that functionality in a Flysystem Plugin would quite possibly be easier/quicker/cleaner

**Comment by CitizenBeta** [comment]
Thanks, I'll check out the Amazon SDK.
