### ISSUE TITLE
Built in adapters and php extension require

### ISSUE THREAD

**Issue by kcassam** [thephpleague/flysystem#750]
2 issues (We have php7.1).

We had this message : 

```
ContextErrorException in FtpFactory.php line 40:
Notice: Use of undefined constant FTP_BINARY - assumed 'FTP_BINARY'

```
* I don't understand why there are ftp adapters built-in. They should be treated like other adapters and be optional, just like for example sftp.

* If not, I think this shoud be in composer.json : 

    "require": {
         "ext-ftp": "to connect to ftp:// server",
    },

Il should be required as well that ftp is activated in php.ini but I don't know how to do that.

I saw there is a unit test for FTP_BINARY constant https://github.com/thephpleague/flysystem/blob/f2ccd52d8e8a271fb340f6636e01d24673e8087b/tests/FtpTests.php#L381

**Comment by frankdejonge** [comment]
The built in adapters don't require any composer dependencies. While it does require the ext-ftp extension for the FTP ones, the overhead of creating a separate package for it is greater than the benefit of having one. For example, this issue is the first one since the creation of flysystem. You can easily mitigate this by adding a project requirement on ext-ftp. I would absolutely advice against that for versioned packages, but extensions like this don't really require such assurances.
