### ISSUE TITLE
is_readable issues with Samba/UNC paths

### ISSUE THREAD

**Issue by SylvesterNielsen** [thephpleague/flysystem#791]
When i create a filesystem using the Local adapter using a samba share/UNC path or mounted drive name i get an error at initialization due to is_readable.
There has been a few bug reports about the issue, but i find no fixes unfortunately.

The adapter and flysystem actually does work, but as the constructor throws an exception we can't use it. 

So i would love to know if it could be possible to have the is_readable part of the constructor as a optional step. I have tested by simply removing the is_readable check from my local version and all seems to work without any issues. Read/write/delete/list.

There's a couple of PHP bugreports about the issue, but as far as i can see no fixes.

* https://bugs.php.net/bug.php?id=49620
* https://bugs.php.net/bug.php?id=62199 
* http://stackoverflow.com/questions/10818770/php-is-readable-fails-on-readable-samba-directory

**Comment by Surt** [comment]
Same problem here. It's a shame. I'm trying to create a docker application that writes on SAMBA paths. The is_readable (from the php bug) is causing the app to not work, but the system CAN write and read. (I can do it with `file_put_contents` for example. The problem is the "is_read"

**Comment by broberts-mrmc** [comment]
For those who have encountered this "UNC path & is_readable()" issue using Flysystem, I wanted to share our solution in case it's helpful.

Since Flysystem's architecture uses the adapter pattern (https://flysystem.thephpleague.com/docs/architecture/), it's inherently extensible in way that can be used to solve this problem.  Basically, to side-step the issue with PHP's built-in function `is_readable()` and UNC/Samba paths, we created a custom "local" adapter that's identical to the one that ships with Flysystem except for the problematic call to `is_readable()`, and placed it within our namespace.

I've attached the source.  Be sure to change the namespace declaration at the top (line 3) to suite your project's namespace/directory structure, and provide an instance of that adapter to Flysystem's `Filesystem()` constructor.

Custom Local Adapter: [Local.zip](https://github.com/thephpleague/flysystem/files/3571714/Local.zip)
