### ISSUE TITLE
WebDav listContents in directory

### ISSUE THREAD

**Issue by anantaramdas** [thephpleague/flysystem#833]
Hi All,

Thanks for wonderful package. I'm trying to get list of directory though WebDav however is it empty
I'm using Laravel GrahamCampbell integration:

`dump(Flysystem::listContents('test'));`
gives me empty array while
`dump(Flysystem::read('/test/test2.txt'));`
gives me content of file.

Could you please help me understand what I'm doing wrong?

Thank you!

**Comment by frankdejonge** [comment]
@anantaramdas could you print out the response from the webdav client? Perhaps there's some filtering issue.

**Comment by frankdejonge** [comment]
Closing this due to lack of response.

**Comment by vietmh** [comment]
Hi @frankdejonge ,

I also got the same problem with @anantaramdas. And in my case, I figured out that the response from the webdav client is filtered by function residesInDirectory() within ContentListingFormatter class. 

The path I got from webdav client is : /remote.php/webdav/SharedFolder/
since the directory checked is just : SharedFolder
then this line of code check the directory name at the very beginning of the webdave path, which will return false.
```
return strpos($entry['path'], $this->directory . '/') === 0;
```
So that it filter out all of my files got from webdav client.

Is there any solution for me to overcome this problem ?
Please be noted that I also use this directory name for other filesystems, so I cannot change this :(

**Comment by frankdejonge** [comment]
@anantaramdas I've been working on the webdav adapter the last few days and it seems only the communication protocol is standardised but the responses and parameters are far from it. I recommend extending the adapter and fixing it there. The one implementation needs it, the other doesn't. Even responses for what collections are are not standard. It's impossible to get everything right for every case. WebDAV is a mess.

**Comment by vietmh** [comment]
Yes, That's what I do at the moment. Thanks.
