### ISSUE TITLE
Unknown actions in AWS S3 V3 IAM policy

### ISSUE THREAD

**Issue by pbowyer** [thephpleague/flysystem#855]
When I create the policy shown on https://flysystem.thephpleague.com/adapter/aws-s3-v3/, Amazon reports that some of the permissions are not known:

![image](https://user-images.githubusercontent.com/89852/31620161-72b1cfa0-b28e-11e7-9bd9-02c86c0f5760.png)

**Comment by frankdejonge** [comment]
@fideloper ... uhhhh HALP?

**Comment by fideloper** [comment]
Ah interesting. Turns out these are actions you can take in the AWS PHP SDK (methods you can call), but aren't explicit actions you can add to a the policy.

* [`CopyObject`](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectCOPY.html) appears to require `s3:GetObject` and `s3:PutObject` (although they aren't explicit about that)
* [`CreateMultipartUpload`](http://docs.aws.amazon.com/AmazonS3/latest/dev/mpuAndPermissions.html) requires potentially a few permissions:
    * `s3:PutObject`
    * `s3:GetObject`
    * `s3:AbortMultipartUpload`
    * `s3:ListMultipartUploadParts`
    * `s3:ListBucketMultipartUploads`
* [`HeadObject`](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectHEAD.html) requires `S3:GetObject` (and seems to suggest also having `s3:ListBucket`
* [`UploadPart`](http://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadUploadPart.html) is once again not explicit but appears to just be a `PUT` request, so I'd guess `s3:PutObject` covers it


So I think we can adjust the policy documented to this:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Stmt1420044805001",
            "Effect": "Allow",
            "Action": [
                "s3:ListObjects",
                "s3:CopyObject",
                "s3:GetObject",
                "s3:DeleteObject",
                "s3:GetObjectAcl",
                "s3:PutObjectAcl",
                "s3:PutObject",
                "s3:ListBucket",
                "s3:AbortMultipartUpload",
                "s3:ListMultipartUploadParts",
                "s3:ListBucketMultipartUploads"
            ],
            "Resource": [
                "arn:aws:s3:::your-bucket-name",
                "arn:aws:s3:::your-bucket-name/*"
            ]
        }
    ]
}
```

This diff:

```diff
diff --git a/original.json b/new.json
index 49db6d6..1e3d1d4 100644
--- a/original.json
+++ b/new.json
@@ -6,16 +6,16 @@
             "Effect": "Allow",
             "Action": [
                 "s3:ListObjects",
-                "s3:HeadObject",
                 "s3:CopyObject",
                 "s3:GetObject",
                 "s3:DeleteObject",
                 "s3:GetObjectAcl",
                 "s3:PutObjectAcl",
                 "s3:PutObject",
-                "s3:CopyObject",
-                "s3:UploadPart",
-                "s3:CreateMultipartUpload"
+                "s3:ListBucket",
+                "s3:AbortMultipartUpload",
+                "s3:ListMultipartUploadParts",
+                "s3:ListBucketMultipartUploads"
             ],
             "Resource": [
                 "arn:aws:s3:::your-bucket-name",

```

**Comment by pbowyer** [comment]
The changes work for me - but then so did the original, so I wasn't exercising the parts of the API needing these additional permissions.

**Comment by fideloper** [comment]
Right on - I'm not sure they're even needed, but they're not necessarily destructive permissions to have open so better have them then not in my opinion (Altho certainly not a hill I'm choosing to die on :D )

**Comment by frankdejonge** [comment]
This was fixed in a PR.
