### ISSUE TITLE
Overwrite file from local to s3

### ISSUE THREAD

**Issue by mkingbe** [thephpleague/flysystem#856]
Hello,

I want to copy a file from local to s3 and I'm using this logic.
 $mountManager->copy('local://storage/file.xml', 's3://file.xml');

How can I overwrite the file if it exists, because now an exception is throw?

Thanks

**Comment by frankdejonge** [comment]
@mkingbe you can first check if the file exists and delete it.

**Comment by mkingbe** [comment]
well, I know that, but is kinda weird of doing it. 
I was starting to look in the library and I saw that:
MountManager.php
` $result = $this->getFilesystem($prefixTo)->writeStream($to, $buffer, $config);`

AwsS3Adapter
`    public function writeStream($path, $resource, Config $config)
    {
        return $this->upload($path, $resource, $config);
    }

    /**
     * Update a file using a stream.
     *
     * @param string   $path
     * @param resource $resource
     * @param Config   $config Config object
     *
     * @return array|false false on failure file meta data on success
     */
    public function updateStream($path, $resource, Config $config)
    {
        return $this->upload($path, $resource, $config);
    }
`
So theoretically writeStream and updateStream is calling same S3Client method (upload).
Why is not overwriting the file in when using $mountManager->copy()
Because is working if I call it standalone: 
$this->get('s3_storage_filesystem')->updateStream('s3://file.xml', fopen('config.php','r+'));


Am I missing something ?

**Comment by ohjimijimijimi** [comment]
Hi, I think the reason is connected to the different assert validation done by [writeStream](https://github.com/thephpleague/flysystem/blob/master/src/Filesystem.php#L82) compared to [updateStream](https://github.com/thephpleague/flysystem/blob/master/src/Filesystem.php#L167). While the first verify that the file doesn't exist, the second does the opposite. 

Taking this into consideration, your `$this->get('s3_storage_filesystem')->updateStream(...` method will overwrite the file because the file exists. It should fail in case the file is not already present on s3. 

You could, as described [here](https://github.com/thephpleague/flysystem/blob/23a0b48a2ec13135b8cac94f47459b83f19a2e43/docs/advanced/performance.md), disable the asserts and use [putStream](https://github.com/thephpleague/flysystem/blob/master/src/Filesystem.php#L108-L123).
