### ISSUE TITLE
Cast to bool stops returning of important Google Drive information, after creating directory.

### ISSUE THREAD

**Issue by mattCreative** [thephpleague/flysystem#870]
https://github.com/thephpleague/flysystem/blob/2a12dff63eca980f103747935b6178862d9c88db/src/Filesystem.php#L262

When you cast the response to bool, you are not letting the important google drive information get passed through after creating the directory.

Please remove the bool cast so we can get the return data from Google Drive.

**Comment by frankdejonge** [comment]
The return value for creation for the filesystem is a boolean, what kind of data do you want back? Perhaps the interface Flysystem has is simply not right for your use-case.

**Comment by frankdejonge** [comment]
You can also call the adapter function directly.

**Comment by frankdejonge** [comment]
There's actually a reason why I didn't create a driver for Flysystem and why it's third party. Google Drive is not a filesystem, it's a database where you can store files. It doesn't behave like a filesystem. The interface for flysystem is based around working with parts (relative to a root) Google Drive doesn't fit this, which is why you want to deal with it differently. However, I think it's better for you to use Google's SDK directly when dealing with Google Drive, or to create a DX wrapper for it yourself to standardise common operations.

**Comment by frankdejonge** [comment]
Thanks for your understanding.
