### ISSUE TITLE
RecursiveDirectoryIterator::__construct(/proc/tty/driver): failed to open dir: Permission denied

### ISSUE THREAD

**Issue by michaelKaefer** [thephpleague/flysystem#880]
Is it possible to avoid this exception (maybe by excluding directories which can't be read by the PHP process because of a lack of permissions?). I can't find it in your docs.

RecursiveDirectoryIterator::__construct(/proc/tty/driver): failed to open dir: Permission denied

My code:
    $filesystem = new Filesystem(new Local('/proc', LOCK_EX, Local::SKIP_LINKS));
    $filesystem->listContents('.', true);

Thank you for an answer, I appreciate it!

**Comment by frankdejonge** [comment]
Hi @michaelKaefer,

Flysystem aims to facilitate standard filesystem operations. It's not a tool to validate if the directory you want to work with is valid, that's just too broad of a scope to be manageable. It's a user's responsibility to verify the directories they are using are writeable and have the correct permissions. Skipping links is one of those features that got in and I've already suffered the consequences from, I'm not looking to add more of those exceptions because in general they hurt more people than they help.

**Comment by michaelKaefer** [comment]
Hi @frankdejonge ,

thank you for your answer! I can understand now :) Still, for me "skipping links" is an helpful optional parameter, and in the end the user has to know how to use it. - My usecase here is to recursively read the directory "/proc", my final question to you: is it a misuse if I use your library for this task? Or if not, how could I accomplish this with Flysystem?

Thank you!

**Comment by frankdejonge** [comment]
You should use Flysystem for file storage, so writing and reading. If I'd be asked to read out the /prod directory I'd just use plain PHP for this task because 1) you'll never move this to S3 and 2) it's not _really_ file storage, it's reading system information from the proc directory. If you don't mind me asking, why are you reading from those directories anyway? I've never done that with PHP ever.

**Comment by michaelKaefer** [comment]
I see. I took another approach, so for my task this is not an issue anymore. But still, if my program has the right to list a directory I as a user would expect that my program can really list it (as it is clear that it can't read a file without permission). So for future questions I will link this issue on Stackoverflow.

Thank you very much!
![download](https://user-images.githubusercontent.com/13886409/34652631-472fc8b6-f3e1-11e7-93e8-e9a6bed3a5f2.png)

PS: I need to read /proc cause I'm writing a library (for "fun") to monitor CPU and memory usage :)

**Comment by frankdejonge** [comment]
@michaelKaefer gotcha! Have fun coding on your project! 👍 

(is it ok to close this issue now?)

**Comment by michaelKaefer** [comment]
@frankdejonge yes, please close it!

Thank you :smile:  :+1:
