### ISSUE TITLE
List contents extension filter?

### ISSUE THREAD

**Issue by delboy1978uk** [thephpleague/flysystem#888]
Is it possible we could allow `listContents()` to filter by file extension (and indeed other things)?

**Comment by frankdejonge** [comment]
@delboy1978uk the filter mechanisms are incompatible across the different filesystems and a generic one will only ever serve a few people right (filters are very use-case specific). People are encourages to just use an array_filter with a custom callback. Yes you'd already have the full result set, but due to the behaviour or most filesystems (except for local ones) this would already be the case.

**Comment by delboy1978uk** [comment]
Hi Frank! Thanks for the explanation, it was only an idea but I see your point! :-)

**Comment by frankdejonge** [comment]
👍  you're welcome!
