### ISSUE TITLE
Local listContents() fails for folders with many files and changing filenames

### ISSUE THREAD

**Issue by drewek-smf** [thephpleague/flysystem#932]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 1.0.44

#### Summary

We have an inbound folder where files are sent via ftp. Periodically, we check with FlySystem (Local Adapter) if there are files to process. During ftp upload, files have ".part" suffix, which is removed as soon as upload is completed.

Now, listContents() first fetches an iterator via getDirectoryIterator(), then iterates the entries. Apparently, it happens that files with ".part" suffix are detected, but during iteration they do not exist anymore. This results in an Exception.

Shouldn't the iteration ignore entries if they don't exist anymore, so finally a reliable list of contents can be returned?

Remark: I know that with local file system, we do not _need_ to use FlySystem. We just want to be cloud-ready with everything.

#### How to reproduce

1) Create a folder with a large number of files (we had this issue with >10,000 files, maybe auto-generate 50,000 files to be on the safe side).
2) Create some script that toggles the filename of (at least) one file as quickly as possible.
3) Perform a listContents() with FlySystem's Local Adapter on this folder.

**Comment by frankdejonge** [comment]
@drewek-smf this is not something we can fix from within filesystem. It depends per case what the right approach would be, which is not something we can accommodate. PHP's internals throw the exception, so all we can do is retry. We can't continue and continuing leads to an unexpected success.

**Comment by mdrewek** [comment]
@frankdejonge I'm waiting for the next issue to occur, to add the detail Stack Trace here. Usually it happens every few days, but it did not occur since I opened this Ticket. However, I'm pretty sure it will happen again soon.

**Comment by mdrewek** [comment]
I am sorry for the delay, we had to wait here for the next big bunch of data. It arrived today, and FlySystem crashed as expected. 

Unfortunately (for us), it might be our own fault. The Exception is definitely thrown in Filesystem::assertPresent(), and this does not seem to be called from within listContents(). But we traverse the listed files ourself, for processing them, and of course if we process thousands of files, later ones might not be available. So it's our responsibility to call has() as file existence check.

So I'm pretty sure that this issue can be closed. Sorry for the inconvenience, apparently I list track of the issue's root cause.

Anyway, this might be something to add to the docs, as it's not so obvious imho that the results of listContents() should not "just" be traversed without existence checks.

**Comment by frankdejonge** [comment]
@mdrewek I'll add a note to the docs, since this is more a PHP issue or a logical error in how this works over time.
