### ISSUE TITLE
Is it possible to get upload progress with ajax ?

### ISSUE THREAD

**Issue by benjaminb-** [thephpleague/flysystem#934]
Hello,

I'm using the S3 adapter and i need to get the percentage of upload progress. Is it possible ? 

I know i can do that with classic upload to the server, but using Flysystem the progress is not working with xhr request ? (or jquery-form, or dropzone.js)

Any tips ?

Thanks :)

**Comment by frankdejonge** [comment]
So there are two thing here. One is the upload progress to your application and one is from your application to S3. For the browser uploasd (XHR) you can use `xhr.upload.addEventListener('progress', function() {});`. This gives you progress notifications for the upload part. The second part is uploading to S3. For this it's possible to get progress updates (https://blog.madewithlove.be/post/stream-progress/) but you can't communicate that progress back to the user because that you terminate the process thus aborting the upload.

**Comment by benjaminb-** [comment]
Thanks for the link,

i'll try to manage that another way, with rabbitMQ worker for the S3 upload part.

Thanks for your time !
