### ISSUE TITLE
PHP Warning:  ftp_chdir(): CWD failed. "/test.txt": directory not found.

### ISSUE THREAD

**Issue by ryanmortier** [thephpleague/flysystem#983]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | latest

#### Summary

I'm using Laravel's Storage class and I'm issuing this command:

```php
Storage::disk('ftp')->put('test.txt', null);
```

And encountering this:

```php
PHP Warning:  ftp_chdir(): CWD failed. "/test.txt": directory not found. in /Users/ryan/Code/signatures/vendor/league/flysystem/src/Adapter/Ftp.php on line 389
```

The command still seems to work and the file is saved to the FTP server but I'm wondering why I'm receiving this PHP warning?

**Comment by frankdejonge** [comment]
@ryanmortier that error should be suppressed, can you check if that's the case for you?

I've checked the following code as an example:

```php
set_error_handler(function (...$e) { var_dump($e); var_dump(error_reporting()); });
function throw_an_error() { trigger_error('WHAT'); return false; }
if (@throw_an_error() === false) echo "LOL";
```

This outputs the error, however the error handler should ignore the error when the `@` suppressor is used, which can be checked if the `error_reporting()` result is `0`.

**Comment by lichtjager** [comment]
I have the same issue in the following code:
`
                                        if ($FtpFileSystem->has($Folder.$FileName))
                                        {
                                            $FtpFileSystem->delete($Folder.$FileName);
                                        }`

**Comment by ryanmortier** [comment]
@frankdejonge I stopped using FTP in my case. Though maybe @lichtjager can provide more details?

**Comment by lichtjager** [comment]
@ryanmortier No, not really, I'm sorry. I use the Flysytem to create a ftp connection, I check if a file exists, and if so, I delete it. Flysystem - while checking if the file exists - uses internally this ftp_chdir() on a file (the file I supply) instead of a folder and of course this fails. Why Flysystem is trying this ftp_chdir() is lost on me.

**Comment by frankdejonge** [comment]
The chdir is needed because there's not a better way to determine if the path is a directory, since ::has supports directories in the FTP side we need to know this. As mentioned in the issue, it's very easy to ignore this warning and your error handling (package or own implementation) should be able to handle this according to the description here: http://php.net/manual/en/function.set-error-handler.php#refsect1-function.set-error-handler-description

**Comment by lichtjager** [comment]
Why don't you just ignore this warning in the package? I find it very strange you leave it to code outside the package to ignore a warning which isn't even obvious where it comes from.

**Comment by frankdejonge** [comment]
@lichtjager because that's not how PHP works, please read the PHP docs. Ignored warning with the @-suppressor are not removed from the logging handler, they are there with a special code, I cannot change how PHP works.

**Comment by spire-mike** [comment]
I'm also confused how this situation is meant to be handled. Can anyone explain how to properly remove that warning? I am using Laravel 8. I added an ftp filesystem disk, and all I'm doing is trying to read a file:

```
$disk = Illuminate\Support\Facades\Storage::disk('ess');
$disk->get('Inventory/Inventory.txt');
```
I do receive the file content as expected, but first I see a warning output:

```
<warning>PHP Warning:  ftp_chdir(): CWD failed. "/Inventory/InventoryWeb.txt": directory not found. in /Users/me/dev/project/vendor/league/flysystem/src/Adapter/Ftp.php on line 397</warning>
```
Are you saying that this is expected behavior?

**Comment by AndreaGero** [comment]
> I'm also confused how this situation is meant to be handled. Can anyone explain how to properly remove that warning? I am using Laravel 8. I added an ftp filesystem disk, and all I'm doing is trying to read a file:
> 
> ```
> $disk = Illuminate\Support\Facades\Storage::disk('ess');
> $disk->get('Inventory/Inventory.txt');
> ```
> 
> I do receive the file content as expected, but first I see a warning output:
> 
> ```
> <warning>PHP Warning:  ftp_chdir(): CWD failed. "/Inventory/InventoryWeb.txt": directory not found. in /Users/me/dev/project/vendor/league/flysystem/src/Adapter/Ftp.php on line 397</warning>
> ```
> 
> Are you saying that this is expected behavior?

I've added this on the Handler class to prevent reporting

```         
$this->reportable(function (Throwable $e) {
            if ($e->getMessage() === 'ftp_chdir(): Invalid number of arguments') {
                return false;
            }
            return $e;
        });
```
